# Generated by Django 4.0 on 2021-12-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
    ]
